FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app

# Crear carpeta de logs dentro del contenedor
RUN mkdir -p /app/logs

# Copiar el JAR del microservicio
COPY target/*.jar app.jar

EXPOSE 86

ENTRYPOINT ["java", "-jar", "app.jar"]
